backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"
site_url: https://paradisepatterns.com
logo_url: https://paradisepatterns.com/images/uploads/p-logo-mini-yellow.svg
collections:
  - label: "Setup"
    name: "setup"
    files:
    - label: "Info"
      name: "info"
      format: 'json'
      file: "content/setup/info.json"
      editor:
        preview: false
      fields:
        - {label: Site Name, name: sitename, widget: string}
        - {label: Site Description, name: sitedescription, widget: string}
        - {label: Your email, name: siteemail, widget: string}
        - {label: Your phone, name: sitephone, widget: string}
    - label: "Links"
      name: "links"
      format: 'json'
      create: true
      file: "content/setup/links.json"
      fields:
        - {label: Link Name, name: linkname, widget: string}
        - {label: Link External, name: linkexternal, widget: string}
        - {label: Link Internal, name: linkinternal, widget: string}