backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/uploads" # Media files will be stored in the repo under/uploads
public_folder: "/uploads"
site_url: https://paradisepatterns.com
logo_url: https://paradisepatterns.com/icon.png
collections:
  - name: "setup"
    label: "Setup"
    files:
    - name: "info"
      label: "Info"
      format: 'json'
      file: "content/setup/info.json"
      editor:
        preview: false
      fields:
        - {label: Site Name, name: sitename, widget: string}
        - {label: Site Description, name: sitedescription, widget: string}
        - {label: Your email, name: siteemail, widget: string, required: false}
        - {label: Your phone, name: sitephone, widget: string, required: false}
    # - name: "colors"
    #   label: "Colors"
    #   format: 'json'
    #   file: "content/setup/colors.json"
    #   fields:
    #     - {label: Primary color, name: primary, widget: string}
    #     - {label: Secondary color, name: secondary, widget: string}
    #     - {label: Background color, name: background, widget: string}
  - name: "links"
    label: "Links"
    label_singular: 'Link'
    # widget: "list"
    format: 'json'
    # file: "content/setup/links.json"
    folder: "content/links/"
    create: true
    slug: '{{order}}-{{pos}}-{{slug}}'
    identifier_field: name
    editor:
        preview: false
    fields:
      - {label: Order, description: 'Put the number in which order you want the link to have and match it according to the others (tip: set the numbers in orders of 10, so that you can fit another one between someday)', name: order, widget: number, min: 1, max: 100, value_type: int, required: true, default: 10 }
      - {label: Link Name, name: name, widget: string, required: true}
      - {label: Link Target, name: target, widget: string, required: true}
      - {label: Open in new tab?, name: newtab, widget: boolean, required: false}
      - {label: Link Position, name: pos, widget: select, default: 'button_row',
        options: [{ label: 'Button row', value: 'button_row' }, { label: 'Social media row', value: 'socialmedia_row' }]}
      - {label: Link icon, description: Upload first then choose a svg icon here if you want to use one, name: icon, widget: image, allow_multiple: false, required: false}
